name: Docker build on tag
env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        TAG_FMT: '^refs/tags/((v(.?[0-9]+){3,4})-?([^+]+)$'

on:
        push:
                tags: [ '*' ]

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build c-lightning
                steps:
                        - name: Setup Environment
                          run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}

                        - name: Show set environment variables
                          run: |
                                  printf "    TAG: %s\n"  "$TAG"

                        - name: Login to Docker Hub
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

                        - name: Checkout project
                          uses: actions/checkout@v2

                        - name: Setup Docker buildx action
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest

                        - name: Show available Docker buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}


                        - name: Run Docker buildx against the tag
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/arm64 \
                                  --tag ${{ secrets.DOCKER_HUB_USER }}/clightning:$TAG \
                                  --output "type=registry" .

                        - name: build against latest
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/arm64 \
                                  --tag ${{ secrets.DOCKER_HUB_USER }}/clightning:latest \
                                  --output "type=registry" .

                        - name: Push to GHCR.io too (ghcr.io/lncm/docker-clightning:TAG)
                          run: |
                                  if [[ ! -z ${{ secrets.MAINTAINER_TOKEN }} ]] && [[ ! -z ${{ secrets.MAINTAINER_USER }} ]]; then
                                      echo "${{ secrets.MAINTAINER_TOKEN }}" | docker login https://ghcr.io -u "${{ secrets.MAINTAINER_USER }}" --password-stdin
                                      echo "Pushing to ghcr.io/lncm/docker-clightning/$TAG ..."
                                      docker buildx build \
                                        --platform linux/amd64,linux/arm64 \
                                        --tag ghcr.io/lncm/docker-clightning:$TAG \
                                        --output "type=registry" .
                                      echo "Pushing to ghcr.io/lncm/docker-clightning:latest ..."
                                      docker buildx build \
                                        --platform linux/amd64,linux/arm64 \
                                        --tag ghcr.io/lncm/docker-clightning:latest \
                                        --output "type=registry" .
                                  else
                                      echo "MAINTAINER_TOKEN and MAINTAINER_USER do no exist! Skipping!"
                                  fi



